### ISSUE TITLE
Action fails, unable to parse JSON output (usage error)

### ISSUE THREAD

**Issue by btrautmann** [CQLabs/dcm-action#150]
I'm running this on CI as follows:

```yaml
- name: Install DCM
  uses: CQLabs/setup-dcm@766aa3df0e01b3821a788beee74fd43cf69f84b0 # v1.1.1
  # For now, only run DCM on the features package until it's configured everywhere
  if: ${{ inputs.package_location == 'features' }}
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
- name: Run DCM
  uses: CQLabs/dcm-action@83726c0c64d41452a9efdcba3d25fc4f97311e88 # v1.0.8
  # For now, only run DCM on the features package until it's configured everywhere
  if: ${{ inputs.package_location == 'features' }}
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    ci_key: ${{ secrets.DCM_CI_KEY }}
    email: ${{ secrets.DCM_EMAIL }}
    folders: ${{ inputs.package_location}}
    package_name: ${{ inputs.package_location }}
```

Version `1.23.1` is installed, but when it runs the following error occurs:

![Screenshot 2024-10-22 at 15 13 17](https://github.com/user-attachments/assets/f93ac6a8-04c0-4e8e-a3b4-f2d5580f2a08)

Note that when run locally on the same version (without `ci-key` and `email` parameters) the command completes successfully.

**Comment by btrautmann** [comment]
Note that the following works as expected:

```yaml
- name: Run DCM
  # Invoking manually until https://github.com/CQLabs/dcm-action/issues/150 is resolved
  run: |
    dcm analyze --ci-key=${{ secrets.DCM_CI_KEY }} --email=${{ secrets.DCM_EMAIL }} \
    --reporter=json --no-congratulate --fatal-warnings --fatal-style --fatal-performance .
```

**Comment by btrautmann** [comment]
So I was able to get past the original issue by prepending the `folders` input with a relative directory based on my theory above. So that became:

```diff
-folders: ${{ inputs.package_location }}
+folders: flutter/${{ inputs.package_location }}
```

However, I then ran into this issue:

![Screenshot 2024-10-22 at 15 48 49](https://github.com/user-attachments/assets/4d07fb40-dc96-4c3f-b88e-f4b414984a9d)

IIRC this is a permissioning issue. I know that there's PAT input support but we prefer to not use PATs. Instead, when needed, we prefer to use Github App tokens. I will try that but suspect it will not work (will report back).

**Comment by btrautmann** [comment]
OK so yeah I don't think there's a path forward here without using a PAT. Can you confirm that's the case? Any chance we can support app tokens?

I think the action items here are:
- **Improve path handling/error messaging:** At the very least, ensure that when a Flutter project is not found, the error is explicit and is handled gracefully.
- **Allow usage of app tokens:** We don't want to use PATs so this would be great!

For now I think we'll invoke it manually and forego the PR comments.

**Comment by incendial** [comment]
> Note that the following works as expected:
> 
> ```yaml
> - name: Run DCM
>   # Invoking manually until https://github.com/CQLabs/dcm-action/issues/150 is resolved
>   run: |
>     dcm analyze --ci-key=${{ secrets.DCM_CI_KEY }} --email=${{ secrets.DCM_EMAIL }} \
>     --reporter=json --no-congratulate --fatal-warnings --fatal-style --fatal-performance .
> ```

This is not the same, you pass `.` and in the error above it's `features`. Since there is the command help output, there is a usage error with one of the passed arguments.

**Comment by btrautmann** [comment]
> > Note that the following works as expected:
> > ```yaml
> > - name: Run DCM
> >   # Invoking manually until https://github.com/CQLabs/dcm-action/issues/150 is resolved
> >   run: |
> >     dcm analyze --ci-key=${{ secrets.DCM_CI_KEY }} --email=${{ secrets.DCM_EMAIL }} \
> >     --reporter=json --no-congratulate --fatal-warnings --fatal-style --fatal-performance .
> > ```
> 
> This is not the same, you pass `.` and in the error above it's `features`. Since there is the command help output, there is a usage error with one of the passed arguments.

Sure, yeah, that was figured out in an above comment. `flutter/${{ inputs.package_location }}` worked correctly. The reason `.` was used in the `run` command was because we had a default working directory set up for this job.

**Comment by incendial** [comment]
> Allow usage of app tokens: We don't want to use PATs so this would be great!

Can you at least test it with PAT to confirm that it works? Also, can you please elaborate on the reason not to use PAT?

**Comment by btrautmann** [comment]
> > Allow usage of app tokens: We don't want to use PATs so this would be great!
> 
> Can you at least test it with PAT to confirm that it works? Also, can you please elaborate on the reason not to use PAT?

I just tried it with a PAT with `repo` and `user#read` access and it did not work. For clarity, here's what I tried:

```yaml
- name: Run DCM
  uses: CQLabs/dcm-action@83726c0c64d41452a9efdcba3d25fc4f97311e88 # v1.0.8
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    ci_key: ${{ secrets.DCM_CI_KEY }}
    github_pat: ${{ secrets.DCM_PAT }}
    email: ${{ secrets.DCM_EMAIL }}
    folders: flutter/${{ inputs.package_location}}
    package_name: ${{ inputs.package_location }}
```

![Screenshot 2024-10-22 at 16 24 20](https://github.com/user-attachments/assets/1b3d8123-0924-43f5-8967-be202e3b8fec)

![Screenshot 2024-10-22 at 16 24 15](https://github.com/user-attachments/assets/7b4011d0-9f22-4bbd-8154-b2a6bdc62d4c)

The error was the same as above (Resource not accessible by integration).

**Regarding PATs vs app tokens:**

We prefer app tokens over PATs due to their inherently short lifetimes (IIRC PATs have a minimum expiration of 7 days) and granular permissioning. It also allows us to not have a PAT assigned to some random machine user, all the tokens fetched/generated by this Github App are associated with that app and that connection is very clear. FWIW supporting apps shouldn't be terribly hard, it's a matter of changing the git protocol, I think. I see you're doing that for PATs already. In our actions we do this via:

```sh
git config --global url."https://x-access-token:${{ steps.get_token.outputs.token }}@github.com".insteadOf "https://github.com" || true
```
